version: '2'

services:
  db:
    restart: always
    image: postgres

    volumes:
      - data-volume:/var/lib/postgresql/data
      - ./initDB.sh:/docker-entrypoint-initdb.d/initDB.sh
      
    expose:
      - "5432"
    ports:
      - "54321:5432"
    environment:
        POSTGRES_DB: user-auth
        POSTGRES_HOST_AUTH_METHOD: trust
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres

  server:
    build: ./server
    command: ./server
    volumes:
      - ./server:/code
    expose:
      - "12345"
    ports:
      - "12345:12345"
    depends_on:
      - db
volumes:
     data-volume: